name: merge dependabot
on: 
  pull_request:
    types: [labeled]

jobs:
  merge:
    if: ${{github.event.label.name == 'dependabot'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "go.mod"
      - run: |
          go mod tidy
      - run: |
          go test ./...
      - run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Run go mod tidy" || exit 0
          git push origin "HEAD:${GITHUB_HEAD_REF}"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}